apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sfs-nec-dev
spec:
  destination:
    namespace: obbt
    server: https://kubernetes.default.svc
  project: obbt
  source:
    helm:
      releaseName: my-release
      # valueFiles:
      # - env/dev/values.yaml
    path: sfs-nec/chart
    repoURL: https://github.com/AlanSMat/argo.git
    targetRevision: main
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
    - Validate=false